### ISSUE TITLE
Halogen 12 release checklist

### ISSUE THREAD

**Issue by KierenP** [KierenP/Halogen#524]
### Development

Blockers:
- [x] Fix `uci perft` command
- [x] Fix printing of castle moves in non chess960

Features:
- [x] Lazy NNUE accumulator
- [x] ~~Make/unmake stack~~

### Testing

Verify supported GUIs:
- [x] Arena

Verify strength:
- [x] STC
- [x] LTC
- [x] Repeating
- [x] SMP
